In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from tqdm import tqdm
import pandas as pd
from acc import get_f1_score, get_user_accuracy, get_producer_accuracy, get_total_accuracy

In [3]:
agg_dir_all = Path('aggregated_validation_dist_2024')
agg_dirs = sorted(list(agg_dir_all.glob('*/')))
sample_agg_dir = agg_dirs[0]
sample_agg_dir

PosixPath('aggregated_validation_dist_2024/builtnewalert__14RNU')

In [4]:
def get_paths(agg_dir: Path):
    veg_status_path = list(agg_dir.glob('dist_hls_veg_*.tif'))[0]
    gen_status_path = list(agg_dir.glob('dist_hls_gen_*.tif'))[0]
    dist_s1_path = list(agg_dir.glob('dist_s1_agg*.tif'))[0]
    dist_s1_count = list(agg_dir.glob('*_count_2024_s1.tif'))[0]
    dist_hls_count = list(agg_dir.glob('*_count_2024_hls.tif'))[0]
    lc_path = list(agg_dir.glob('*glad_lc_mask.tif'))[0]
    return {'veg_status': veg_status_path,
            'gen_status': gen_status_path,
            'dist_s1': dist_s1_path,
            'dist_s1_count': dist_s1_count,
            'dist_hls_count': dist_hls_count,
            'lc': lc_path}

In [5]:
def open_one(path: Path) -> np.ndarray: 
    with rasterio.open(path) as src:
        return src.read(1)

def compute_accuracy(ref_arr, pred_arr, valid_mask):
    ref_arr = ref_arr[valid_mask]
    pred_arr = pred_arr[valid_mask]

    f1 = get_f1_score(ref_arr, pred_arr)
    user_acc = get_user_accuracy(ref_arr, pred_arr)
    producer_acc = get_producer_accuracy(ref_arr, pred_arr)
    total_acc = get_total_accuracy(ref_arr, pred_arr)
    count = np.sum(valid_mask)

    return {'f1': float(f1), 
            'user_acc': float(user_acc), 
            'producer_acc': float(producer_acc), 
            'total_acc': float(total_acc), 
            'count': int(count)}

    

def analysis_for_agg_dir(agg_dir: Path, min_s1_obs: int = 10, min_hls_obs: int = 20):
    
    out_data = {}

    path_dict = get_paths(agg_dir)
    veg_status = open_one(path_dict['veg_status'])
    gen_status = open_one(path_dict['gen_status'])
    dist_s1 = open_one(path_dict['dist_s1'])
    dist_s1_count = open_one(path_dict['dist_s1_count'])
    dist_hls_count = open_one(path_dict['dist_hls_count'])
    lc = open_one(path_dict['lc'])

    s1_mask_count = dist_s1_count > min_s1_obs
    hls_mask_count = dist_hls_count > min_hls_obs
    veg_confirmed_all = (np.isin(veg_status, [3, 6])).astype(np.uint8)
    #veg_confirmed_high = (np.isin(veg_status, [6])).astype(np.uint8)
    gen_confirmed_all = (np.isin(gen_status, [3, 6])).astype(np.uint8)
    # gen_confirmed_high = (np.isin(gen_status, [6])).astype(np.uint8)
    dist_s1_confirmed_all = (np.isin(dist_s1, [3, 6])).astype(np.uint8)

    mask_count = s1_mask_count & hls_mask_count

    mask_dict = {'desert': np.isin(lc, [0, 1]),
                 'semi_arid': np.isin(lc, list(range(2, 19))),
                 'dense_short_vegetation': np.isin(lc, list(range(20, 25))),
                 'tree_cover_all': np.isin(lc, list(range(25, 39))),
                 'tree_cover_above_10m': np.isin(lc, list(range(32, 39))),
                 'wetland_tree_cover': np.isin(lc, list(range(125, 149))),
                 'wetland_vegetation_sparse': np.isin(lc, list(range(102, 119))),
                 'wetland_other': np.isin(lc, list(range(119, 125)) + [100, 101]),
                 'surface_water': np.isin(lc, list(range(200, 209))),
                 'built_up': lc == 250,
                 'cropland': lc == 244,
                 'ocean': lc == 254,
                 'snow_ice': lc == 241,
                 }

    out_data['accuracy_gen_all_confirmed'] = compute_accuracy(gen_confirmed_all, dist_s1_confirmed_all, mask_count)
    # out_data['accuracy_gen_high_confirmed'] = compute_accuracy(veg_confirmed_high, dist_s1_confirmed_all, mask_count)
    out_data['accuracy_veg_all_confirmed'] = compute_accuracy(veg_confirmed_all, dist_s1_confirmed_all, mask_count)
    # out_data['accuracy_veg_high_confirmed'] = compute_accuracy(veg_confirmed_high, dist_s1_confirmed_all, mask_count)
    for key, mask in mask_dict.items():
        mask_lc_valid = mask & mask_count
        out_data[f'accuracy_gen_all_confirmed_{key}'] = compute_accuracy(gen_confirmed_all, dist_s1_confirmed_all, mask_lc_valid)
        out_data[f'accuracy_veg_all_confirmed_{key}'] = compute_accuracy(veg_confirmed_all, dist_s1_confirmed_all, mask_lc_valid)
        # out_data[f'accuracy_gen_high_confirmed_{key}'] = compute_accuracy(gen_confirmed_high, dist_s1_confirmed_all, mask_lc_valid)
        # out_data[f'accuracy_veg_high_confirmed_{key}'] = compute_accuracy(veg_confirmed_high, dist_s1_confirmed_all, mask_lc_valid)
    out_data['umd_name'] = agg_dir.stem
    return out_data

In [6]:
sample_agg_dir = agg_dirs[70]
print(sample_agg_dir)
analysis_for_agg_dir(sample_agg_dir)

aggregated_validation_dist_2024/treelosswet__49RGN

/Users/cmarshak/bekaert-team/dist-s1-research/marshak/Zg_validation_variation/acc.py:14: RuntimeWarning: invalid value encountered in scalar divide
  f1 = 2 * tp / (2 * tp + fp + fn)
/Users/cmarshak/bekaert-team/dist-s1-research/marshak/Zg_validation_variation/acc.py:20: RuntimeWarning: invalid value encountered in scalar divide
  user_accuracy = tp / (tp + fp)
/Users/cmarshak/bekaert-team/dist-s1-research/marshak/Zg_validation_variation/acc.py:26: RuntimeWarning: invalid value encountered in scalar divide
  producer_accuracy = tp / (tp + fn)
/Users/cmarshak/bekaert-team/dist-s1-research/marshak/Zg_validation_variation/acc.py:32: RuntimeWarning: invalid value encountered in scalar divide
  total_accuracy = (tp + tn) / (tp + tn + fp + fn)

{'accuracy_gen_all_confirmed': {'f1': 0.23539831817372797,
  'user_acc': 0.17237174838755107,
  'producer_acc': 0.3710819278005606,
  'total_acc': 0.9309841016427683,
  'count': 13133684},
 'accuracy_veg_all_confirmed': {'f1': 0.23410780745655893,
  'user_acc': 0.22834204053698473,
  'producer_acc': 0.24017229505853613,
  'total_acc': 0.9079150221674285,
  'count': 13133684},
 'accuracy_gen_all_confirmed_desert': {'f1': 0.0,
  'user_acc': 0.0,
  'producer_acc': 0.0,
  'total_acc': 0.8787878787878788,
  'count': 33},
 'accuracy_veg_all_confirmed_desert': {'f1': 0.0,
  'user_acc': 0.0,
  'producer_acc': 0.0,
  'total_acc': 0.9393939393939394,
  'count': 33},
 'accuracy_gen_all_confirmed_semi_arid': {'f1': 0.21245421245421245,
  'user_acc': 0.14720812182741116,
  'producer_acc': 0.3815789473684211,
  'total_acc': 0.895224171539961,
  'count': 2052},
 'accuracy_veg_all_confirmed_semi_arid': {'f1': 0.05172413793103448,
  'user_acc': 0.030456852791878174,
  'producer_acc': 0.17142857142857143,
  'total_acc': 0.8927875243664717,
  'count': 2052},
 'accuracy_gen_all_confirmed_dense_short_vegetation': {'f1': 0.3225856576800559,
  'user_acc': 0.2954739538855679,
  'producer_acc': 0.3551753635585971,
  'total_acc': 0.9658337246491057,
  'count': 1531159},
 'accuracy_veg_all_confirmed_dense_short_vegetation': {'f1': 0.28706792361614697,
  'user_acc': 0.49300218237024385,
  'producer_acc': 0.20248638431785188,
  'total_acc': 0.9325811362503829,
  'count': 1531159},
 'accuracy_gen_all_confirmed_tree_cover_all': {'f1': 0.19374169820241138,
  'user_acc': 0.14705370624677658,
  'producer_acc': 0.28386620846002986,
  'total_acc': 0.936265080006588,
  'count': 6180866},
 'accuracy_veg_all_confirmed_tree_cover_all': {'f1': 0.2082287238371911,
  'user_acc': 0.20666310406323207,
  'producer_acc': 0.20981824605232444,
  'total_acc': 0.9181587175648203,
  'count': 6180866},
 'accuracy_gen_all_confirmed_tree_cover_above_10m': {'f1': 0.08796863430230772,
  'user_acc': 0.054588574090543344,
  'producer_acc': 0.22642238577877707,
  'total_acc': 0.9259147872730841,
  'count': 3607724},
 'accuracy_veg_all_confirmed_tree_cover_above_10m': {'f1': 0.12880869285413726,
  'user_acc': 0.09917418371236184,
  'producer_acc': 0.1837008448450333,
  'total_acc': 0.912195888599017,
  'count': 3607724},
 'accuracy_gen_all_confirmed_wetland_tree_cover': {'f1': 0.4009246636239701,
  'user_acc': 0.5540629095674967,
  'producer_acc': 0.314107922355345,
  'total_acc': 0.9284576670701408,
  'count': 141273},
 'accuracy_veg_all_confirmed_wetland_tree_cover': {'f1': 0.36320084446429296,
  'user_acc': 0.7327981651376146,
  'producer_acc': 0.2414314244076213,
  'total_acc': 0.8889738308098505,
  'count': 141273},
 'accuracy_gen_all_confirmed_wetland_vegetation_sparse': {'f1': 0.4013840830449827,
  'user_acc': 0.2680221811460259,
  'producer_acc': 0.7988980716253443,
  'total_acc': 0.7277305634246144,
  'count': 3177},
 'accuracy_veg_all_confirmed_wetland_vegetation_sparse': {'f1': 0.30057803468208094,
  'user_acc': 0.21626617375231053,
  'producer_acc': 0.4926315789473684,
  'total_acc': 0.6572237960339944,
  'count': 3177},
 'accuracy_gen_all_confirmed_wetland_other': {'f1': 0.2782275366879309,
  'user_acc': 0.1915170132325142,
  'producer_acc': 0.5084161003659174,
  'total_acc': 0.9113488633568744,
  'count': 284610},
 'accuracy_veg_all_confirmed_wetland_other': {'f1': 0.3510365251727542,
  'user_acc': 0.42013232514177695,
  'producer_acc': 0.3014581213970838,
  'total_acc': 0.8614103510066407,
  'count': 284610},
 'accuracy_gen_all_confirmed_surface_water': {'f1': 0.3353287148099156,
  'user_acc': 0.23666984898912913,
  'producer_acc': 0.5750426123620705,
  'total_acc': 0.8217728530190643,
  'count': 998041},
 'accuracy_veg_all_confirmed_surface_water': {'f1': 0.2516206031177706,
  'user_acc': 0.1623564658287137,
  'producer_acc': 0.558912715849872,
  'total_acc': 0.816540603041358,
  'count': 998041},
 'accuracy_gen_all_confirmed_built_up': {'f1': 0.14607691634836867,
  'user_acc': 0.10560708263069139,
  'producer_acc': 0.23683464120260944,
  'total_acc': 0.9697258977593939,
  'count': 1934789},
 'accuracy_veg_all_confirmed_built_up': {'f1': 0.14031011898848325,
  'user_acc': 0.19350758853288363,
  'producer_acc': 0.11005478762303238,
  'total_acc': 0.9418577426272322,
  'count': 1934789},
 'accuracy_gen_all_confirmed_cropland': {'f1': 0.2616346554654183,
  'user_acc': 0.1888429101748734,
  'producer_acc': 0.42574195433484996,
  'total_acc': 0.9182464783081963,
  'count': 1408343},
 'accuracy_veg_all_confirmed_cropland': {'f1': 0.31747654074586745,
  'user_acc': 0.36519750789198396,
  'producer_acc': 0.28078579308872204,
  'total_acc': 0.8795620101069129,
  'count': 1408343},
 'accuracy_gen_all_confirmed_ocean': {'f1': 0.18181818181818182,
  'user_acc': 0.16666666666666666,
  'producer_acc': 0.2,
  'total_acc': 0.8714285714285714,
  'count': 70},
 'accuracy_veg_all_confirmed_ocean': {'f1': 0.15384615384615385,
  'user_acc': 0.16666666666666666,
  'producer_acc': 0.14285714285714285,
  'total_acc': 0.8428571428571429,
  'count': 70},
 'accuracy_gen_all_confirmed_snow_ice': {'f1': nan,
  'user_acc': nan,
  'producer_acc': nan,
  'total_acc': nan,
  'count': 0},
 'accuracy_veg_all_confirmed_snow_ice': {'f1': nan,
  'user_acc': nan,
  'producer_acc': nan,
  'total_acc': nan,
  'count': 0},
 'umd_name': 'treelosswet__49RGN'}

In [7]:
all_data = [analysis_for_agg_dir(agg_dir) for agg_dir in tqdm(agg_dirs)]

100%|██████████| 85/85 [01:24<00:00,  1.01it/s]

In [8]:
import json

with open('acc.json', 'w') as f:
    json.dump(all_data, f, indent=2)

# Aggregations

## Agg by Type

In [9]:
types = [agg_dir.stem.split('__')[0] for agg_dir in agg_dirs]
types = list(set(types))
types

['waternew',
 'gen',
 'builtnewalert',
 'fire',
 'treelosswet',
 'cropnew',
 'oldcrop_short',
 'other',
 'treelossTF',
 'wetshort']

In [10]:
df_acc = pd.json_normalize(all_data)
df_acc.head()

,umd_name,accuracy_gen_all_confirmed.f1,accuracy_gen_all_confirmed.user_acc,accuracy_gen_all_confirmed.producer_acc,accuracy_gen_all_confirmed.total_acc,accuracy_gen_all_confirmed.count,accuracy_veg_all_confirmed.f1,accuracy_veg_all_confirmed.user_acc,accuracy_veg_all_confirmed.producer_acc,accuracy_veg_all_confirmed.total_acc,...,accuracy_gen_all_confirmed_snow_ice.f1,accuracy_gen_all_confirmed_snow_ice.user_acc,accuracy_gen_all_confirmed_snow_ice.producer_acc,accuracy_gen_all_confirmed_snow_ice.total_acc,accuracy_gen_all_confirmed_snow_ice.count,accuracy_veg_all_confirmed_snow_ice.f1,accuracy_veg_all_confirmed_snow_ice.user_acc,accuracy_veg_all_confirmed_snow_ice.producer_acc,accuracy_veg_all_confirmed_snow_ice.total_acc,accuracy_veg_all_confirmed_snow_ice.count
0,builtnewalert__14RNU,0.178646,0.308600,0.125709,0.958266,13392161,0.120196,0.259173,0.078241,0.944200,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
1,builtnewalert__16SBF,0.201754,0.133620,0.411669,0.823637,13392666,0.340996,0.302235,0.391161,0.805148,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
2,builtnewalert__22KFA,0.668697,0.593488,0.765734,0.897117,231544,0.621869,0.690530,0.565628,0.853086,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,builtnewalert__22LDQ,0.433678,0.380843,0.503533,0.882231,12719570,0.405349,0.575186,0.312945,0.800185,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
4,builtnewalert__22MDT,0.194235,0.172788,0.221760,0.926765,11091406,0.242595,0.496196,0.160543,0.841721,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

In [11]:
df_acc['umd_type'] = df_acc.umd_name.map(lambda x: x.split('__')[0])

In [12]:
df_by_type = df_acc[[col for col in df_acc.columns if col != 'umd_name']].groupby('umd_type').mean()

In [13]:
df_by_type.to_csv('acc_by_type.csv')

In [14]:
df_acc.to_csv('acc_by_tile.csv')

# Agg by Mask

In [15]:
import pandas as pd

acc_cols = [c for c in df_acc.select_dtypes(include=['float']) if 'count' not in c]
count_cols = [c for c in df_acc.columns if 'count' in c]
groups = list(set([c.split('.')[0] for c in acc_cols]))
acc_types = list(set([c.split('.')[1] for c in acc_cols]))
acc_types

['f1', 'user_acc', 'total_acc', 'producer_acc']

In [16]:
df_acc.head()

,umd_name,accuracy_gen_all_confirmed.f1,accuracy_gen_all_confirmed.user_acc,accuracy_gen_all_confirmed.producer_acc,accuracy_gen_all_confirmed.total_acc,accuracy_gen_all_confirmed.count,accuracy_veg_all_confirmed.f1,accuracy_veg_all_confirmed.user_acc,accuracy_veg_all_confirmed.producer_acc,accuracy_veg_all_confirmed.total_acc,...,accuracy_gen_all_confirmed_snow_ice.user_acc,accuracy_gen_all_confirmed_snow_ice.producer_acc,accuracy_gen_all_confirmed_snow_ice.total_acc,accuracy_gen_all_confirmed_snow_ice.count,accuracy_veg_all_confirmed_snow_ice.f1,accuracy_veg_all_confirmed_snow_ice.user_acc,accuracy_veg_all_confirmed_snow_ice.producer_acc,accuracy_veg_all_confirmed_snow_ice.total_acc,accuracy_veg_all_confirmed_snow_ice.count,umd_type
0,builtnewalert__14RNU,0.178646,0.308600,0.125709,0.958266,13392161,0.120196,0.259173,0.078241,0.944200,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,builtnewalert
1,builtnewalert__16SBF,0.201754,0.133620,0.411669,0.823637,13392666,0.340996,0.302235,0.391161,0.805148,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,builtnewalert
2,builtnewalert__22KFA,0.668697,0.593488,0.765734,0.897117,231544,0.621869,0.690530,0.565628,0.853086,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,builtnewalert
3,builtnewalert__22LDQ,0.433678,0.380843,0.503533,0.882231,12719570,0.405349,0.575186,0.312945,0.800185,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,builtnewalert
4,builtnewalert__22MDT,0.194235,0.172788,0.221760,0.926765,11091406,0.242595,0.496196,0.160543,0.841721,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,builtnewalert

In [17]:
def lc_extractor(group: str):
    if '.' in group:
        group = group.split('.')[0]
    if 'confirmed_' in group:
        return group.split('confirmed_')[1]
    else:
        return 'all_classes'
    
def status_extractor(group: str):
    if '_gen_' in group:
        return 'gen'
    elif '_veg_' in group:
        return 'veg'
    else:
        raise ValueError(f'Unknown group: {group}')

In [18]:
def format_acc(df: pd.DataFrame, acc_col: str):

    acc_type = acc_col.split('.')[1]
    df_expanded_group = df[['umd_name', acc_col]].reset_index(drop=True)
    df_expanded_group = df_expanded_group.rename(columns={acc_col: 'acc'})
    df_expanded_group['lc_class'] = lc_extractor(acc_col)
    df_expanded_group['hls_type'] = status_extractor(acc_col)
    df_expanded_group['acc_type'] = acc_type
    return df_expanded_group

dfs = [format_acc(df_acc, col) for col in df_acc.columns if pd.api.types.is_numeric_dtype(df_acc[col]) and 'count' not in col]

In [19]:
df_acc_expanded = pd.concat(dfs, axis=0)
df_acc_expanded.sort_values(by='acc', ascending=False, inplace=True)
df_acc_expanded.head()

             umd_name  acc                   lc_class hls_type      acc_type
33         gen__47TNH  1.0              surface_water      gen  producer_acc
23        fire__22LDR  1.0  wetland_vegetation_sparse      gen     total_acc
60  treelossTF__35VLF  1.0                     desert      veg     total_acc
59  treelossTF__33NUF  1.0  wetland_vegetation_sparse      gen     total_acc
33         gen__47TNH  1.0     dense_short_vegetation      gen     total_acc

In [20]:
def get_acc_by_group(group: str, 
                     acc_type: str,
                     ref_acc_column_key: str = 'f1',
                     top_percent: float = 0.8):
    count_col = group + '.count'
    acc_col = group + '.' + acc_type
    if acc_type != ref_acc_column_key:
        ref_acc_col = group + '.' + ref_acc_column_key
        cols = [count_col, acc_col, ref_acc_col]
    else:
        ref_acc_col = acc_col
        cols = [count_col, acc_col]
    df_acc_temp = df_acc[cols].sort_values(by=ref_acc_col, ascending=False)
    n = df_acc_temp.shape[0]
    df_acc_temp = df_acc_temp.iloc[:int(n * top_percent)]
    total_count = df_acc_temp[count_col].sum()
    weighted_acc = (df_acc_temp[acc_col] * df_acc_temp[count_col]).sum() / total_count
    return float(weighted_acc)

In [21]:
agg_by_tile = [{'group': g, 'acc_type': a, 'acc': get_acc_by_group(g, a)}  for a in acc_types for g in groups]
df_agg_by_tile = pd.DataFrame(agg_by_tile)

df_agg_by_tile_f = df_agg_by_tile.copy()
df_agg_by_tile_f['lc_class'] = df_agg_by_tile_f['group'].map(lc_extractor)
df_agg_by_tile_f['hls_type'] = df_agg_by_tile_f['group'].map(status_extractor)
df_agg_by_tile_f.drop(columns=['group'], inplace=True)
df_agg_by_tile_f.head()

  acc_type       acc                lc_class hls_type
0       f1  0.333655          tree_cover_all      veg
1       f1  0.008431                  desert      veg
2       f1  0.360249           wetland_other      veg
3       f1  0.290536  dense_short_vegetation      veg
4       f1  0.046578                   ocean      veg

In [22]:
df_agg_by_tile_f = df_agg_by_tile_f.sort_values(by=['acc_type','acc'], ascending=False)
df_agg_by_tile_f = df_agg_by_tile_f[['acc_type', 'lc_class', 'hls_type', 'acc']]
df_agg_by_tile_f.to_csv('acc_by_tile_group_best.csv', index=False)

In [23]:
dfs = []
for acc_type in acc_types:
    df_agg_by_tile_temp = df_agg_by_tile_f[df_agg_by_tile_f['acc_type'] == acc_type].reset_index(drop=True)
    df_agg_by_tile_temp.drop(columns=['acc_type'], inplace=True)
    df_agg_by_tile_temp.rename(columns={'acc': acc_type}, inplace=True)
    dfs.append(df_agg_by_tile_temp)

df_all = pd.DataFrame(columns=['lc_class', 'hls_type'])
for df in dfs[:]:
    df_all = pd.merge(df_all, df, on=['lc_class', 'hls_type'], how='right') 
df_all.sort_values(by=['user_acc'], ascending=False, inplace=True)
df_all.head()

                lc_class hls_type        f1  user_acc  total_acc  producer_acc
23    wetland_tree_cover      veg  0.348435  0.689469   0.814895      0.277308
18  tree_cover_above_10m      veg  0.366355  0.557727   0.901500      0.340346
21        tree_cover_all      veg  0.333655  0.530702   0.884830      0.300911
19    wetland_tree_cover      gen  0.324895  0.488417   0.846320      0.335133
9   tree_cover_above_10m      gen  0.356688  0.397613   0.903188      0.432946

In [24]:
df_all_user = df_all.sort_values(by=['user_acc'], ascending=False)
df_all_user = df_all_user[df_all_user['producer_acc'] > .2].reset_index(drop=True)
df_all_user.head()

               lc_class hls_type        f1  user_acc  total_acc  producer_acc
0    wetland_tree_cover      veg  0.348435  0.689469   0.814895      0.277308
1  tree_cover_above_10m      veg  0.366355  0.557727   0.901500      0.340346
2        tree_cover_all      veg  0.333655  0.530702   0.884830      0.300911
3    wetland_tree_cover      gen  0.324895  0.488417   0.846320      0.335133
4  tree_cover_above_10m      gen  0.356688  0.397613   0.903188      0.432946

In [25]:
df_all_prod = df_all.sort_values(by=['producer_acc'], ascending=False)
df_all_prod = df_all_prod[df_all_prod['user_acc'] > .2].reset_index(drop=True)
df_all_prod.head()

               lc_class hls_type        f1  user_acc  total_acc  producer_acc
0         wetland_other      gen  0.315785  0.228900   0.666476      0.611289
1         wetland_other      veg  0.360249  0.306287   0.663326      0.571381
2         surface_water      gen  0.294379  0.230759   0.832900      0.537016
3           all_classes      gen  0.287680  0.239310   0.847129      0.445748
4  tree_cover_above_10m      gen  0.356688  0.397613   0.903188      0.432946

In [26]:
df_all_no_lc = df_all[df_all['lc_class'] == 'all_classes'].sort_values(by=['user_acc'], ascending=False)
df_all_no_lc.head()

       lc_class hls_type        f1  user_acc  total_acc  producer_acc
14  all_classes      veg  0.324252  0.352195   0.823221      0.388081
6   all_classes      gen  0.287680  0.239310   0.847129      0.445748

In [27]:
from excel_export import df_to_excel_with_gradient
df_to_excel_with_gradient(df_all_user.head(5), 'acc_by_tile_group_best_user.xlsx')
df_to_excel_with_gradient(df_all_prod.head(5), 'acc_by_tile_group_best_producer.xlsx')
df_to_excel_with_gradient(df_all_no_lc, 'acc_by_tile_group_best_no_lc.xlsx')
df_to_excel_with_gradient(df_all_prod[df_all_prod['hls_type'] == 'veg'].head(5), 'acc_by_tile_group_best_producer_veg.xlsx')

In [28]:
df_acc_expanded.head()

             umd_name  acc                   lc_class hls_type      acc_type
33         gen__47TNH  1.0              surface_water      gen  producer_acc
23        fire__22LDR  1.0  wetland_vegetation_sparse      gen     total_acc
60  treelossTF__35VLF  1.0                     desert      veg     total_acc
59  treelossTF__33NUF  1.0  wetland_vegetation_sparse      gen     total_acc
33         gen__47TNH  1.0     dense_short_vegetation      gen     total_acc

In [30]:
n_to_show = 25

for a in ['user_acc', 'producer_acc', 'f1']:
    print('########')
    print(a)
    df_acc_temp = df_acc_expanded[df_acc_expanded['acc_type'] == a].reset_index(drop=True)
    df_acc_temp = df_acc_temp[df_acc_temp['acc'] < 1]
    df_acc_temp = df_acc_temp[df_acc_temp['lc_class'] == 'all_classes']
    df_acc_temp = df_acc_temp.sort_values(by='acc', ascending=False).reset_index(drop=True)
    df_acc_temp = df_acc_temp[df_acc_temp['hls_type'] == 'veg'].reset_index(drop=True)
    print('best')
    print(df_acc_temp.head(n_to_show))
    print('worst')
    print(df_acc_temp.tail(n_to_show))

########
user_acc
best
                umd_name       acc     lc_class hls_type  acc_type
0            fire__20LNJ  0.901472  all_classes      veg  user_acc
1     treelosswet__50NPL  0.797787  all_classes      veg  user_acc
2   oldcrop_short__51KVV  0.736749  all_classes      veg  user_acc
3     treelosswet__20LMM  0.712562  all_classes      veg  user_acc
4   builtnewalert__22KFA  0.690530  all_classes      veg  user_acc
5   builtnewalert__22MGB  0.668276  all_classes      veg  user_acc
6     treelosswet__20KPF  0.647369  all_classes      veg  user_acc
7            fire__22LDR  0.616397  all_classes      veg  user_acc
8     treelosswet__20KNG  0.607144  all_classes      veg  user_acc
9     treelosswet__17SQT  0.593400  all_classes      veg  user_acc
10    treelosswet__48MUD  0.584045  all_classes      veg  user_acc
11           fire__52UCF  0.582900  all_classes      veg  user_acc
12  builtnewalert__22LDQ  0.575186  all_classes      veg  user_acc
13       wetshort__22LEQ  0.573601  all_classes      veg  user_acc
14        cropnew__21LWC  0.533027  all_classes      veg  user_acc
15    treelosswet__47NRG  0.516597  all_classes      veg  user_acc
16     treelossTF__10TDT  0.506557  all_classes      veg  user_acc
17       wetshort__20TLP  0.496835  all_classes      veg  user_acc
18  builtnewalert__22MDT  0.496196  all_classes      veg  user_acc
19        cropnew__20HMD  0.468754  all_classes      veg  user_acc
20  builtnewalert__44PKB  0.460426  all_classes      veg  user_acc
21     treelossTF__28PHR  0.439046  all_classes      veg  user_acc
22  oldcrop_short__20LQL  0.397181  all_classes      veg  user_acc
23     treelossTF__19NBD  0.397050  all_classes      veg  user_acc
24  builtnewalert__50SMF  0.396105  all_classes      veg  user_acc
worst
                umd_name       acc     lc_class hls_type  acc_type
58       wetshort__21HUC  0.193191  all_classes      veg  user_acc
59       waternew__53KKU  0.151705  all_classes      veg  user_acc
60            gen__45TUK  0.147201  all_classes      veg  user_acc
61     treelossTF__29SPC  0.139854  all_classes      veg  user_acc
62          other__31UCQ  0.134192  all_classes      veg  user_acc
63  oldcrop_short__50KNB  0.131202  all_classes      veg  user_acc
64        cropnew__36RTS  0.130069  all_classes      veg  user_acc
65  builtnewalert__60HTF  0.127065  all_classes      veg  user_acc
66          other__30SUD  0.125526  all_classes      veg  user_acc
67        cropnew__20HMJ  0.114834  all_classes      veg  user_acc
68  builtnewalert__43QFE  0.113442  all_classes      veg  user_acc
69       waternew__44QKM  0.107823  all_classes      veg  user_acc
70    treelosswet__20MMA  0.104513  all_classes      veg  user_acc
71       waternew__53KQV  0.084063  all_classes      veg  user_acc
72          other__12UUD  0.081157  all_classes      veg  user_acc
73        cropnew__31PGN  0.055164  all_classes      veg  user_acc
74     treelossTF__37NEG  0.042046  all_classes      veg  user_acc
75            gen__11TLH  0.019117  all_classes      veg  user_acc
76            gen__32VMQ  0.011695  all_classes      veg  user_acc
77            gen__40SFC  0.001778  all_classes      veg  user_acc
78            gen__12STA  0.001270  all_classes      veg  user_acc
79            gen__30SXB  0.000094  all_classes      veg  user_acc
80            gen__47TNH  0.000002  all_classes      veg  user_acc
81            gen__33QTU  0.000000  all_classes      veg  user_acc
82          other__38RMN  0.000000  all_classes      veg  user_acc
########
producer_acc
best
                umd_name       acc     lc_class hls_type      acc_type
0        waternew__33PUR  0.841538  all_classes      veg  producer_acc
1   oldcrop_short__51KVV  0.799384  all_classes      veg  producer_acc
2   oldcrop_short__36UXA  0.782170  all_classes      veg  producer_acc
3        waternew__53KKU  0.769784  all_classes      veg  producer_acc
4        wetshort__36PVR  0.756033  all_classes      veg  producer_acc
5             gen__11TLH  0.749275  all_classes      veg  producer_acc
6   oldcrop_short__35UNR  0.747986  all_classes      veg  producer_acc
7           other__31UCQ  0.744657  all_classes      veg  producer_acc
8           other__21JVJ  0.716246  all_classes      veg  producer_acc
9     treelosswet__48MUD  0.669588  all_classes      veg  producer_acc
10           fire__20LNJ  0.638327  all_classes      veg  producer_acc
11            gen__30SXB  0.628099  all_classes      veg  producer_acc
12    treelosswet__50NPL  0.605063  all_classes      veg  producer_acc
13     treelossTF__10TDT  0.592662  all_classes      veg  producer_acc
14     treelossTF__35VLF  0.590060  all_classes      veg  producer_acc
15       waternew__17MPT  0.574019  all_classes      veg  producer_acc
16  builtnewalert__22KFA  0.565628  all_classes      veg  producer_acc
17  builtnewalert__22MGB  0.559667  all_classes      veg  producer_acc
18  oldcrop_short__38ULE  0.547345  all_classes      veg  producer_acc
19           fire__17UPT  0.544251  all_classes      veg  producer_acc
20            gen__45TUK  0.539822  all_classes      veg  producer_acc
21     treelossTF__28PHR  0.526551  all_classes      veg  producer_acc
22       wetshort__20TLP  0.516265  all_classes      veg  producer_acc
23       waternew__36NUN  0.491211  all_classes      veg  producer_acc
24       wetshort__21HUC  0.469289  all_classes      veg  producer_acc
worst
                umd_name       acc     lc_class hls_type      acc_type
56        cropnew__20HMD  0.245898  all_classes      veg  producer_acc
57        cropnew__20HMJ  0.240508  all_classes      veg  producer_acc
58    treelosswet__49RGN  0.240172  all_classes      veg  producer_acc
59        cropnew__17TPG  0.237805  all_classes      veg  producer_acc
60    treelosswet__20KPF  0.236677  all_classes      veg  producer_acc
61          other__19TBG  0.217004  all_classes      veg  producer_acc
62        cropnew__35MRM  0.214915  all_classes      veg  producer_acc
63            gen__40SFC  0.194906  all_classes      veg  producer_acc
64          other__54HXH  0.186948  all_classes      veg  producer_acc
65  oldcrop_short__20LQL  0.173085  all_classes      veg  producer_acc
66  builtnewalert__22MDT  0.160543  all_classes      veg  producer_acc
67  oldcrop_short__21HUU  0.144654  all_classes      veg  producer_acc
68       waternew__44QKM  0.135192  all_classes      veg  producer_acc
69          other__48RWV  0.123479  all_classes      veg  producer_acc
70  builtnewalert__43QFE  0.121071  all_classes      veg  producer_acc
71          other__38KNB  0.113967  all_classes      veg  producer_acc
72          other__53LKC  0.113107  all_classes      veg  producer_acc
73       wetshort__37VDH  0.106320  all_classes      veg  producer_acc
74     treelossTF__37NEG  0.105001  all_classes      veg  producer_acc
75     treelossTF__13RCK  0.084417  all_classes      veg  producer_acc
76  builtnewalert__14RNU  0.078241  all_classes      veg  producer_acc
77            gen__47TNH  0.076923  all_classes      veg  producer_acc
78        cropnew__31PGN  0.069443  all_classes      veg  producer_acc
79  oldcrop_short__50KNB  0.057241  all_classes      veg  producer_acc
80          other__30SUD  0.055395  all_classes      veg  producer_acc
########
f1
best
                umd_name       acc     lc_class hls_type acc_type
0   oldcrop_short__51KVV  0.766789  all_classes      veg       f1
1            fire__20LNJ  0.747415  all_classes      veg       f1
2     treelosswet__50NPL  0.688187  all_classes      veg       f1
3     treelosswet__48MUD  0.623898  all_classes      veg       f1
4   builtnewalert__22KFA  0.621869  all_classes      veg       f1
5   builtnewalert__22MGB  0.609168  all_classes      veg       f1
6      treelossTF__10TDT  0.546237  all_classes      veg       f1
7        wetshort__22LEQ  0.508489  all_classes      veg       f1
8        wetshort__20TLP  0.506364  all_classes      veg       f1
9        wetshort__36PVR  0.488268  all_classes      veg       f1
10     treelossTF__28PHR  0.478833  all_classes      veg       f1
11           fire__22LDR  0.463394  all_classes      veg       f1
12    treelosswet__47NRG  0.461532  all_classes      veg       f1
13    treelosswet__20KNG  0.457947  all_classes      veg       f1
14  oldcrop_short__36UXA  0.437378  all_classes      veg       f1
15  oldcrop_short__35UNR  0.430248  all_classes      veg       f1
16     treelossTF__19NBD  0.429341  all_classes      veg       f1
17     treelossTF__33NUF  0.407063  all_classes      veg       f1
18  builtnewalert__22LDQ  0.405349  all_classes      veg       f1
19        cropnew__21LWC  0.385465  all_classes      veg       f1
20           fire__52UCF  0.378286  all_classes      veg       f1
21    treelosswet__20LMM  0.372821  all_classes      veg       f1
22    treelosswet__17SQT  0.362820  all_classes      veg       f1
23           fire__17UPT  0.356061  all_classes      veg       f1
24     treelossTF__33MXS  0.353777  all_classes      veg       f1
worst
                umd_name       acc     lc_class hls_type acc_type
58          other__48RWV  0.179622  all_classes      veg       f1
59        cropnew__36RTS  0.172875  all_classes      veg       f1
60          other__53LKC  0.164869  all_classes      veg       f1
61       wetshort__37VDH  0.164579  all_classes      veg       f1
62    treelosswet__20MMA  0.160239  all_classes      veg       f1
63        cropnew__20HMJ  0.155447  all_classes      veg       f1
64          other__38KNB  0.147897  all_classes      veg       f1
65          other__12UUD  0.137378  all_classes      veg       f1
66       waternew__53KQV  0.136551  all_classes      veg       f1
67     treelossTF__13RCK  0.134029  all_classes      veg       f1
68  builtnewalert__14RNU  0.120196  all_classes      veg       f1
69       waternew__44QKM  0.119966  all_classes      veg       f1
70  builtnewalert__43QFE  0.117132  all_classes      veg       f1
71  oldcrop_short__50KNB  0.079707  all_classes      veg       f1
72          other__30SUD  0.076868  all_classes      veg       f1
73        cropnew__31PGN  0.061486  all_classes      veg       f1
74     treelossTF__37NEG  0.060047  all_classes      veg       f1
75            gen__11TLH  0.037283  all_classes      veg       f1
76            gen__32VMQ  0.022606  all_classes      veg       f1
77            gen__40SFC  0.003525  all_classes      veg       f1
78            gen__12STA  0.002533  all_classes      veg       f1
79            gen__30SXB  0.000189  all_classes      veg       f1
80            gen__47TNH  0.000004  all_classes      veg       f1
81          other__38RMN  0.000000  all_classes      veg       f1
82            gen__33QTU  0.000000  all_classes      veg       f1